<Project Sdk="Microsoft.NET.Sdk.Web">

 <PropertyGroup>
  <OutputType>Exe</OutputType>
  <TargetFramework>net10.0</TargetFramework>
  <ImplicitUsings>enable</ImplicitUsings>
  <Nullable>enable</Nullable>
  <LangVersion>preview</LangVersion>
 </PropertyGroup>

 <ItemGroup>
  <Compile Remove="bin\**;obj\**;tests\**" />
  <Content Remove="bin\**;obj\**;tests\**" />
  <None Remove="bin\**;obj\**;tests\**" />
 </ItemGroup>

 <ItemGroup>
  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
 </ItemGroup>

</Project>
